### ISSUE TITLE
Changing parameters of the launch's product causes the update to fail

### ISSUE THREAD

**Issue by eamonnfaherty** [awslabs/aws-service-catalog-puppet#121]

**Comment by eamonnfaherty** [comment]
fixed

**Comment by jordan-evans** [comment]
I'm still seeing this issue in `0.22.0`. I've removed a parameter from a product, and rolling out an update to the product is causing an error:

```
Traceback (most recent call last): 
 
  File "/usr/local/lib/python3.7/site-packages/luigi/worker.py", line 199, in run 
    new_deps = self._run_get_new_deps() 
 
  File "/usr/local/lib/python3.7/site-packages/luigi/worker.py", line 139, in _run_get_new_deps 
    task_gen = self.task.run() 
 
  File "/usr/local/lib/python3.7/site-packages/servicecatalog_puppet/luigi_tasks_and_targets.py", line 243, in run 
    self.version, 
 
  File "/usr/local/lib/python3.7/site-packages/servicecatalog_puppet/aws.py", line 212, in provision_product 
    raise Exception(f"[{launch_name}] {account_id}:{region} :: " 
 
Exception: [my_launch] 012345678910:eu-west-2 :: Plan failed: Error calling API cloudformation:CreateChangeSet. ErrorCode: ValidationError, Message: Parameters: [MyParameter] do not exist in the template 
```
