### ISSUE TITLE
ServiceCatalog Puppet fails due to PutEvents limit reached

### ISSUE THREAD

**Issue by vc00778402** [awslabs/aws-service-catalog-puppet#537]
The pipeline failed due to the putevents limit exhausted. The data on manifest file is large to parse hence it failed.

# Steps to reproduce
1. Just run the pipeline with the attached manifest file

# Expected results
 Should create IAM roles on accounts added on manifest file

# Actual results
botocore.exceptions.ClientError: An error occurred (ValidationException) when calling the PutEvents operation: Total size of the entries in the request is over the limit.
[puppet-pipeline-logs.zip](https://github.com/awslabs/aws-service-catalog-puppet/files/9159117/puppet-pipeline-logs.zip)
[manifest.zip](https://github.com/awslabs/aws-service-catalog-puppet/files/9159118/manifest.zip)

**Comment by eamonnfaherty** [comment]
fixed in 0.184.0

**Comment by vc00778402** [comment]
The issue still persists after upgrading to 0.184.0. Kindly assist.

![image](https://user-images.githubusercontent.com/109735599/189118673-414f11db-e092-4ed6-a4a8-2f71b36dab94.png)

**Comment by eamonnfaherty** [comment]
Can you share the cloud trail event for the error please. 

The error should not be blocking anything. The error occurs after the workflow has completed and is a reporting action. 

There is a workaround of turning off ops center integration.

**Comment by eamonnfaherty** [comment]
can you share the cloudtrail event or your artefacts for the run where you saw the failure.

**Comment by vc00778402** [comment]
Hi Eamonn,

I've attached the logs and the Artifacts.
Meanwhile can you explain how do we go about "turning off event bridge integration" that you mentioned as a workaround?

[Artifacts.zip](https://github.com/awslabs/aws-service-catalog-puppet/files/9559630/Artifacts.zip)
[Cloudwatch Logs.txt](https://github.com/awslabs/aws-service-catalog-puppet/files/9559634/Cloudwatch.Logs.txt)

**Comment by eamonnfaherty** [comment]
it is a parameter in the initialiser stack.  you should be able to turn it off easily.

from your artifacts I can see the launch_parameters and manifest_parameters for your launch xxx-core-managed-vpc-db-connected are significantly larger (27x) than expected.  This is valid but sort of an edge case.  I will need to make an update to get this working.  I should be able to drop a release by Thursday.

I do not think I will need a CloudTrail event as I have this but if you manage to find it please share it.

**Comment by Murali5189** [comment]
@eamonnfaherty  Is there any update on this issue  ?

**Comment by eamonnfaherty** [comment]
this is now fixed
